service: nike-devops-demo

frameworkVersion: '2'

custom:
  contactsTable: contactsTable
  productsTable: productsTable
  csvImportBucketName: nike-${self:provider.stage}.csv.import.centreum.com
  logBucketName: nike-${self:provider.stage}-logs.centreum.com
  tableThroughputs:
    production: "50"
    dev: "5"

provider:
  stage: ${opt:stage, 'dev'}
  timeout: 30
  name: aws
  runtime: java8
  region: us-east-1
  environment:
    CONTACTS_TABLE: ${self:custom.contactsTable}
    PRODUCTS_TABLE: ${self:custom.productsTable}
    SUBNET_ID: !Ref PrivateSubnetC
    EMR_LOGS_BUCKET:
      Ref: LogBucket
    CSV_IMPORT_BUCKET: ${self:custom.csvImportBucketName}

  vpc:
    securityGroupIds:
      - !Ref VpcDefaultSecurityGroup
    subnetIds:
      - !Ref PrivateSubnetA
      - !Ref PrivateSubnetB
      - !Ref PrivateSubnetC
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "iam:PassRole"
          Resource:
            - arn:aws:iam::#{AWS::AccountId}:role/EMR_DefaultRole
            - arn:aws:iam::#{AWS::AccountId}:role/EMR_EC2_DefaultRole

        - Effect: "Allow"
          Action:
            - "elasticmapreduce:RunJobFlow"
            # - "autoscaling-plans:*"
            # - "application-autoscaling:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            - "Fn::Join":
                - ""
                - - "arn:aws:s3:::"
                  - ${self:custom.csvImportBucketName}
                  - "/*"
            - !Join ['', ['arn:aws:s3:::', !Ref LogBucket, '/emr-logs/*']]
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource:
            - "Fn::GetAtt": [ContactsTable, Arn]
            - "Fn::Join":
                - "/"
                - - { "Fn::GetAtt": [ContactsTable, Arn] }
                  - "index/*"
            - "Fn::GetAtt": [ProductsTable, Arn]
            - "Fn::Join":
                - "/"
                - - { "Fn::GetAtt": [ProductsTable, Arn] }
                  - "index/*"

functions:
  - ${file(resources/functions/python_emr.yml)}
  - ${file(resources/functions/java_api.yml)}

resources:
  - ${file(resources/s3.yml)}
  - ${file(resources/vpc.yml)}
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/emr.yml)}

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'
  include:
    - "scripts/*.q"
    - "src/*.py"
  exclude:
    - "**/*"
plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-offline
